# Generated by Django 3.2.13 on 2022-06-02 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedTablesNew',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('reservation', models.ForeignKey(db_column='Reservation', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.eventreservations')),
                ('reservedtables', models.ForeignKey(db_column='ReservedTables', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.table')),
            ],
            options={
                'db_table': 'reserved_tables_new',
                'managed': True,
                'unique_together': {('reservation', 'reservedtables')},
            },
        ),
    ]
