# Generated by Django 3.2.13 on 2022-05-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerexpenditure',
            name='productbought',
        ),
        migrations.AddField(
            model_name='customerexpenditure',
            name='unit',
            field=models.CharField(blank=True, db_column='Unit', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='customerexpenditure',
            name='amount',
            field=models.DecimalField(db_column='Amount', decimal_places=2, max_digits=12),
        ),
    ]
