# Generated by Django 3.2.13 on 2022-05-30 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0004_meni_akcija'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('idsetup', models.AutoField(db_column='idSetup', primary_key=True, serialize=False)),
                ('description', models.CharField(db_column='Description', default='', max_length=100)),
            ],
            options={
                'db_table': 'setup',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SetupTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setup', models.ForeignKey(db_column='Setup', on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.setup')),
                ('table', models.ForeignKey(db_column='Table', on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.table')),
            ],
            options={
                'db_table': 'setuptables',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='events',
            name='setup',
            field=models.ForeignKey(db_column='Setup', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.setup'),
        ),
    ]
