# Generated by Django 3.2.13 on 2022-05-30 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0006_auto_20220530_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='waiter',
            field=models.ForeignKey(db_column='Waiter', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.users'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='preference',
            unique_together=set(),
        ),
    ]
