# Generated by Django 3.2.13 on 2022-05-30 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0007_auto_20220530_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, db_column='name', max_length=30),
        ),
    ]
