# Generated by Django 3.2.13 on 2022-05-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0010_alter_table_idtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='exparationdate',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='type',
        ),
    ]
