# Generated by Django 3.2.13 on 2022-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0012_auto_20220530_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='end',
            field=models.TimeField(db_column='End'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='start',
            field=models.TimeField(db_column='Start'),
        ),
    ]
