# Generated by Django 3.2.13 on 2022-05-30 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0013_auto_20220530_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weighter',
            new_name='waiter',
        ),
    ]
