# Generated by Django 3.2.13 on 2022-05-19 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20220519_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meni',
            options={'managed': False},
        ),
    ]
