# Generated by Django 3.2.13 on 2022-05-19 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_meni_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meni',
            options={'managed': False, 'ordering': ('subtype',)},
        ),
    ]
