# Generated by Django 3.2.13 on 2022-05-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_meni_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'managed': True},
        ),
    ]
