# Generated by Django 3.2.13 on 2022-05-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_coupon_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='name',
            field=models.CharField(db_column='Name', default='Ime', max_length=100),
        ),
        migrations.AddField(
            model_name='coupon',
            name='type',
            field=models.CharField(db_column='Type', default='Popust', max_length=20),
        ),
    ]
