# Generated by Django 3.2.13 on 2022-05-22 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20220522_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userscoupons',
            options={'managed': False},
        ),
    ]
