# Generated by Django 3.2.13 on 2022-05-31 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0004_alter_preference_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preference',
            options={'managed': True},
        ),
    ]
