# Generated by Django 3.2.13 on 2022-05-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0006_auto_20220531_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='idpref',
            field=models.AutoField(db_column='idpreference', primary_key=True, serialize=False),
        ),
    ]
