# Generated by Django 3.2.13 on 2022-05-31 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0008_auto_20220531_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='id',
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferedshift',
            field=models.ForeignKey(db_column='PreferedShift', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='filmkafe.shift'),
        ),
    ]
