# Generated by Django 3.2.13 on 2022-05-31 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0009_auto_20220531_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='preferedshift',
            field=models.OneToOneField(db_column='PreferedShift', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='filmkafe.shift'),
        ),
    ]
