# Generated by Django 4.0.4 on 2022-06-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtables',
            name='reservedtables',
            field=models.ForeignKey(db_column='ReservedTables', on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.table'),
        ),
    ]
