# Generated by Django 3.2.13 on 2022-06-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0002_reservedtablesnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='points',
            field=models.IntegerField(db_column='points', default=100),
        ),
    ]
