# Generated by Django 4.0.4 on 2022-06-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0002_alter_reservedtables_reservedtables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='shift',
            field=models.ForeignKey(db_column='shift', on_delete=django.db.models.deletion.DO_NOTHING, to='filmkafe.shift'),
        ),
    ]
