# Generated by Django 4.0.4 on 2022-06-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0003_alter_schedule_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='day',
            field=models.DateField(db_column='Day'),
        ),
    ]
