# Generated by Django 4.0.4 on 2022-06-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0004_alter_preferences_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='day',
            field=models.DateTimeField(db_column='Day'),
        ),
    ]
