# Generated by Django 3.2.13 on 2022-05-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0005_auto_20220530_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='description',
        ),
        migrations.RemoveField(
            model_name='table',
            name='group',
        ),
        migrations.AddField(
            model_name='setup',
            name='name',
            field=models.CharField(db_column='Name', default='', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, db_column='Group', max_length=30),
        ),
    ]
