# Generated by Django 4.0.4 on 2022-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0006_productsold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsold',
            name='name',
            field=models.CharField(db_column='Name', default='', max_length=50),
        ),
    ]
