# Generated by Django 4.0.4 on 2022-06-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0007_productsold_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerexpenditure',
            old_name='unit',
            new_name='userInfo',
        ),
    ]
