# Generated by Django 3.2.13 on 2022-05-30 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0008_alter_table_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtables',
            name='reservedtables',
            field=models.ForeignKey(db_column='ReservedTables', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.table'),
        ),
        migrations.AlterField(
            model_name='setuptables',
            name='setup',
            field=models.ForeignKey(db_column='Setup', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.setup'),
        ),
        migrations.AlterField(
            model_name='setuptables',
            name='table',
            field=models.ForeignKey(db_column='Table', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.table'),
        ),
    ]
