# Generated by Django 4.0.4 on 2022-06-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0008_rename_unit_customerexpenditure_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexpenditure',
            name='userInfo',
            field=models.CharField(blank=True, db_column='userInfo', max_length=45, null=True),
        ),
    ]
