# Generated by Django 4.0.4 on 2022-06-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0009_alter_customerexpenditure_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterWorkHours',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('waiterInfo', models.CharField(db_column='userInfo', max_length=45)),
                ('day', models.DateTimeField(db_column='day')),
                ('hours', models.PositiveIntegerField()),
                ('waiter', models.ForeignKey(db_column='WaiterId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WaiterWorkHours',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaiterPermit',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('day', models.DateTimeField(db_column='day')),
                ('waiter', models.ForeignKey(db_column='WaiterId', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'WaiterPermit',
                'managed': True,
            },
        ),
    ]
