# Generated by Django 4.0.4 on 2022-06-06 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0010_waiterworkhours_waiterpermit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterworkhours',
            name='waiterInfo',
            field=models.CharField(db_column='waiterInfo', max_length=45),
        ),
    ]
