# Generated by Django 3.2.13 on 2022-05-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0011_auto_20220530_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='imagepath',
            field=models.CharField(db_column='image', default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='phone',
            field=models.CharField(db_column='Phone', default=1, max_length=15),
            preserve_default=False,
        ),
    ]
