# Generated by Django 4.0.4 on 2022-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0012_alter_waiterworkhours_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='product',
            field=models.PositiveIntegerField(),
        ),
    ]
