# Generated by Django 4.0.4 on 2022-06-06 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filmkafe', '0013_alter_productsold_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsold',
            name='product',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, to='filmkafe.product'),
        ),
    ]
